USE ROLE ACCOUNTADMIN;

CREATE ROLE DBT_EXECUTOR_ROLE
COMMENT = 'Role for the users running DBT models';

USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH
TO ROLE DBT_EXECUTOR_ROLE;

USE ROLE SYSADMIN;

ALTER WAREHOUSE "COMPUTE_WH" SET
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
COMMENT = 'Default Warehouse';

CREATE USER IF NOT EXISTS DBT_EXECUTOR
COMMENT = 'User running DBT commands'
    PASSWORD = 'Mati12345!@#$%'
    DEFAULT_WAREHOUSE = 'COMPUTE_WH'
    DEFAULT_ROLE = 'DBT_EXECUTOR_ROLE';

GRANT ROLE DBT_EXECUTOR_ROLE TO USER DBT_EXECUTOR;

GRANT ROLE DBT_EXECUTOR_ROLE TO USER JANSNOWFLAKE;

USE ROLE DBT_EXECUTOR_ROLE;

CREATE DATABASE PORTFOLIO_TRACKING
COMMENT = 'DB for the portfolio tracking project';

CREATE SCHEMA PORTFOLIO_TRACKING.SOURCE_DATA;

create or replace TABLE PORTFOLIO_TRACKING.SOURCE_DATA.ABC_BANK_POSITION (
	ACCOUNTID VARCHAR(16777216),
	SYMBOL VARCHAR(16777216),
	DESCRIPTION VARCHAR(16777216),
	EXCHANGE VARCHAR(16777216),
	REPORT_DATE DATE,
	QUANTITY NUMBER(38,0),
	COST_BASE NUMBER(38,5),
	POSITION_VALUE NUMBER(38,5),
	CURRENCY VARCHAR(16777216)
);


CREATE FILE FORMAT PORTFOLIO_TRACKING.SOURCE_DATA.ABC_BANK_CSV_FILE_FORMAT
TYPE = 'CSV'
COMPRESSION = 'AUTO'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '\042'
TRIM_SPACE = FALSE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
ESCAPE = 'NONE'
ESCAPE_UNENCLOSED_FIELD = '\134'
DATE_FORMAT = 'AUTO'
TIMESTAMP_FORMAT = 'AUTO'
NULL_IF = ('\\N')
;
